apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx-too

generatorOptions:
  # disableNameSuffixHash is true disables the default behavior of adding a
  # suffix to the names of generated resources that is a hash of
  # the resource contents.
  disableNameSuffixHash: true

configMapGenerator:
  - name: ingress-nginx-too-values-cm
    files:
      - ingress-nginx-too-values-cm.yaml

resources:
  - release.yaml
