apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx-too
spec:
  releaseName: ingress-nginx-too
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      #https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
      version: "3.30.0"
  interval: 0h5m0s
  install:
    remediation:
      retries: 3
  #https://github.com/kubernetes/ingress-nginx/blob/master/charts/ingress-nginx/values.yaml
  values:
    controller:
      service:
        type: NodePort
  valuesFrom:
  - kind: ConfigMap
    name: ingress-nginx-too-values-cm
    valuesKey: ingress-nginx-too-values-cm.yaml
