---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gatekeeper-system
resources:
  - ../../_shared_/opa-gatekeeper-base/gatekeeper.yaml
patchesStrategicMerge:
  - gatekeeper-patch.yaml
