---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gatekeeper-system
resources:
  - ./opa-policies/k8srequiredlabels_template.yaml
  - ./opa-policies/all_pod_must_have_gatekeeper_namespaceselector.yaml
