apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: policy
  namespace: gatekeeper-system
spec:
  dependsOn:
    - name: opa-gatekeeper
  interval: 5m
  path: "./policy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
