apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: opa-gatekeeper
  namespace: flux-system
spec:
  interval: 5m
  path: "./infrastructure/opa/opa-gatekeeper"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: gatekeeper-controller-manager
      namespace: gatekeeper-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: policy
  namespace: flux-system
spec:
  dependsOn:
    - name: opa-gatekeeper
  interval: 5m
  path: "./policy/opa-policies"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
