apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: policy
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
  interval: 1m
  path: "./policy/opa-policies"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
