apiVersion: v1
data:
    password: ENC[AES256_GCM,data:RHnGa/+vP5wG4HkX,iv:SgycB3GNW8j5oQDTTpO02lJ6zXcmiRll8CWxu9bZ46Y=,tag:9Yz+hwoxSwzEOcp5dze4kw==,type:str]
    user: ENC[AES256_GCM,data:S67qtA==,iv:9Ks96hD706IF2OQItH1ldjacdZWzULBUWfN6pwM1eaQ=,tag:buV69QjUC0dZHrRtf+PVOQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: another-one
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-26T00:38:23Z"
    mac: ENC[AES256_GCM,data:dFIYAyX1rqrHJpZ5fH2srbu4IdkIUbTZR7bvq2QPc/MZm/bZdjh8q+mnnzGeMlWi+OgOlTjvjt3IejZ6VFw9q3akKiJVpkaKwjWk8ZnRF7ZTA/V71ZhAwC5qyyjqMiV46sQkGCrFljEdJIVmAWr3UKnYB6z0xntqpLdEboniX0Y=,iv:7CzWTFNCJueU4oXPbfhgDnJrE3yBP2KRnsqzR4aheVg=,tag:img7+sgI9peVDbQwnJ6d0g==,type:str]
    pgp:
        - created_at: "2021-07-26T01:15:17Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+6f4KEjD2gnAQ//ZQme7g1Q9UntZCvSjxCZIvwoLAm5BlJCdYJwdkP50eCN
            KSFzn+OUdN+bgq3MHBxd8bPLBTqk+VAGrdi0OdTVhG+7jejL0pRMtcfZZhDW/E5p
            HH9M62wNUGv0y/O74mCGPKvzQXFbL2r3HTGTrL/Hw44C7NknYiXGb4XrFndoPpwS
            GbB5f8m1ufC+qCYk+EzOb234o40PtxiHdL621TPwsF0/6WVWts/3KVCMqavF9Wzr
            eECJ3yq3asRdpNHzPBznqdSyfSBMgbpVDRtPYvHgN5otNS3gshdS2y27K0tEJWcY
            VlI1DR3USGB7tC/3wvVui58JIGT79MYCGI6qmmCTSHXv+AOwQy5iYbiU7O98vmaB
            UhLCIz7OnlHwyNE9jczv7gvl+FSesuqJXaxtQDr5M8iJRW/Qkg3MFE+Wxi14BtNM
            qGrUooBCoRf6sLWIXDoKzKdN59Sg055OTI8oNTYYMLNiYyAmdRVEgwm3NAqrc8aI
            doh6t8XDzFcMj2Glw9J+6/MsAyipIpM8fnvCdcFqChZChB9zSKYbB/u6Kr3pG3eA
            /wdM3fUxSEacXaRLAF5Ippe+UqZgioMqSAehuiWdfjp0ZqZ+wYaUjpneza8Yj0Eu
            26CgoByN9S3eJsDfHK7UaYucTGpK7rLb884TuKgDqiXbNFW9f+wDhwhlGwyMPHLS
            XAGhuvRcILavBRB5WfnACNKwNYltVuhfk0XOkBA7fSf+pJCWyOjVUb39OAT6d27A
            ktrAhQmUm2T8QbAolgI7N9TD+P5k9NjbFgNFnmL2jwLmDs2OEWoh/yclkwVd
            =1Fy5
            -----END PGP MESSAGE-----
          fp: 8BDCB97533DF8A6907F5CD22DC9A8583D90E8FD5
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
