apiVersion: v1
data:
    password: ENC[AES256_GCM,data:RHnGa/+vP5wG4HkX,iv:SgycB3GNW8j5oQDTTpO02lJ6zXcmiRll8CWxu9bZ46Y=,tag:9Yz+hwoxSwzEOcp5dze4kw==,type:str]
    user: ENC[AES256_GCM,data:S67qtA==,iv:9Ks96hD706IF2OQItH1ldjacdZWzULBUWfN6pwM1eaQ=,tag:buV69QjUC0dZHrRtf+PVOQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: another-one
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-26T00:38:23Z"
    mac: ENC[AES256_GCM,data:dFIYAyX1rqrHJpZ5fH2srbu4IdkIUbTZR7bvq2QPc/MZm/bZdjh8q+mnnzGeMlWi+OgOlTjvjt3IejZ6VFw9q3akKiJVpkaKwjWk8ZnRF7ZTA/V71ZhAwC5qyyjqMiV46sQkGCrFljEdJIVmAWr3UKnYB6z0xntqpLdEboniX0Y=,iv:7CzWTFNCJueU4oXPbfhgDnJrE3yBP2KRnsqzR4aheVg=,tag:img7+sgI9peVDbQwnJ6d0g==,type:str]
    pgp:
        - created_at: "2021-07-26T00:38:22Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0h6RICzxlSZARAAr1JozBN+j/QdxCbm4y0yLNc6A41Abd2Qfi66ymNHfx5/
            yVclbW0qYoHAP8jxi30/CyCyBua3az8RV0NuokfZtXRTNm+ZyFreO6m/z4PE7Ctq
            9FoQv4Wilymp/ZAVAFdWK1j1SfGVuVMe3X3GirqLpT+bBGa4NRdbnI2yQQqUGkqr
            /PJSEpgchc0xj5tTr/89I5LsEbrdOOdRflXnK9q+iBUOaktiHA6+NFV5Lv34vfnd
            9EyY//4tLWpZmGkH9e1wdDsUS6GRCTFrbRz4R+kmfSv9rtzFm5UY2u7LUc5wLdfE
            ka555a3r0nsDbldRXC/JeJvDmGBXLkhPq00jdm0/pRf+Iqz4k1N24o7uDtpm7aiL
            eudVKbT6FiX0gwsUwToA4uVx82MwjStfYzTWMEnfGDbXySVakayTzmXA5VY9ZvqY
            Pwn/WDV+wu16ROyVQGfAeYjXugQhPAAO+QB9APLLqE1GrHZkt3aw3C4IwRdJV3lR
            kHSu1uJPHDFR19IhSbyDeySZxcFqCuJoTggtfv8hLXVXrLZYVDhtZ8aTXl27jn+8
            orHnOk9LZbyD6v3AMGW+406f6YTYL83Qt87tZqps5NwHeEcK7xojCwTw85FsmqFO
            XOmVQa2z51atbEdDOA38BPV5i2kwIShJ+nD4X7l74HMfIrdaS3DawESJCwSgTiTS
            XAHC8nmgChHVRDk0GaqlyeI5sJozUTnrGGq5xgjnO2m1HKMhfO2KeBBVBrbqfHnW
            QehwBG7VIlkIneNRpbIBdFkJSbffUz6wfOEyPsAwYE53SNzHDnMymq6PlOec
            =4d4m
            -----END PGP MESSAGE-----
          fp: E60C780414D6837363C95074C7A84018BE05E526
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
