apiVersion: v1
data:
    password: ENC[AES256_GCM,data:noB0WupWhVdxdwcP,iv:rsgAxFKRgT09UNohIqhtyF6Agi/qGoAqt7sqWxzQdSw=,tag:lVQJ+/R/M1oCKdTUMNBEBw==,type:str]
    user: ENC[AES256_GCM,data:lUDoVOR6p/8=,iv:shCdl9C4W1KmLoi8bqLTyoH6kilY5m9naBuOVWmieEo=,tag:skUu5xy4ENd2+CFv/s0Fpg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: basic-auth
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-25T13:29:18Z"
    mac: ENC[AES256_GCM,data:f2RR7fSoa7WlkBU0yoQ1+O2ra/d07gqmUzPnnhSwJROyy/E9LA56M08QwVJDXtMq71nQFJ98N2dMuiojHfOy+me9HXxeAGbA1Fj9AVPRmDxBOb73t/7CY4Cbdhh6n3XUzturx+Pi0BHCDEjH9ltj5PGZClTm8iJC0eS+LruyWDg=,iv:bt2EeDApp13vpKzooo+femnVPEmBJeUbotcurWDXvH8=,tag:+bTvi+avqB989eBGW53Jcw==,type:str]
    pgp:
        - created_at: "2021-07-25T13:27:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+Q4Pf8wD4a7AQ//cFHm1o2Vsqp0O1p7pRahit1GaVjektK2RycpQKS9ybdx
            kPwqVeFzbUqur/eASvjD48/WYs/09JHE7f8Vat+HfunuinZPA3+JMdQ/iE+I5fTb
            NWazUZrfj9gCij05ipuhg2G6xrUpfcxPcGosDESIeUZpo4IK0NTQcFzZS2AQmuq9
            Vk53PUYztu2uT61FZkFsNbxjfKW6zwHBYG/6Mi029PLTiHK+Q9Ayyw8hzBL/OPCp
            fcIzuyHU4xbzujOmBGGmyXKYk5W7UTqaq337WyFFrvZFJRjGBqqSdb2iMwIZTKWy
            LSRdiBr8y9uZKVqDfkmqUeReef9hpCXeWWBi7rHccSj8CBT85Gm2+dz+EM/SlQLF
            xMmyfce4MQ0Mr1d+jA9/H+SzLq43rfaWYNuDJcEV5s1DpvjwW+wKzBNz9ln2ZzFT
            tNo04upOufwGLHyMy7Zp1Q4gta12EUYuZa81C7Olwfn7g/qW0sqn3e10hv1ZL4nD
            /33cT7hRIytjA19FHqfBRaubfm+4QcTl1UCtjULp2d3DecPc/IulSj3kCr38nB//
            PU5P72M0xpNejt/+oMwDuoxWoAgFlcVabj9OEU3eVsVWTEY0bseRhIK7h0y2t/Fv
            DGplgTBu94ywBH/1hBiSVjB7/lrenV32Cnl3jiNG4aA52MhRrDW64vR0CLbRqZ7S
            XgEq82/LlD6+N/SRIYmvAEKOUf2Z286u0vhpcD3mF8Oj/OIgvfMnoh0qfAHiDyhT
            D6CTzAn2vPPcGdg+aTijijFmqnhxbDKllRDa6FG9e4ol0wgZv3c0QIoOVdm9bRg=
            =UrkZ
            -----END PGP MESSAGE-----
          fp: 5AC96F45A255B1D84B0A74F07E3C6299058D7FC3
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
