apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  endpoints:
  - port: metrics
#  jobLabel: jobLabel
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx

