apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
spec:
  releaseName: kured
  chart:
    spec:
      chart: kured
      sourceRef:
        kind: HelmRepository
        name: kured
        namespace: flux-system
      version: "2.4.3"
  interval: 0h5m0s
  install:
    remediation:
      retries: 3
  # Default values
  values:
    configuration:
      period: "1h0m0s"           # reboot check period (default 1h0m0s)
      rebootDays: [mo,tu,we,th]  # only reboot on these days (default [su,mo,tu,we,th,fr,sa])
      startTime: "12:00"         # only reboot after this time of day (default "0:00")
      endTime: "20:00"           # only reboot before this time of day (default "23:59")
      timeZone: "UTC"            # time-zone to use (valid zones from "time" golang package)
    metrics:
      create: true
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/metrics"
      prometheus.io/port: "8080"
