apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: gatekeeper-controller-manager
  namespace: gatekeeper-system
  labels:
    prometheusPodMonitor: include
spec:
  namespaceSelector:
    matchNames:
      - gatekeeper-system
  selector:
    matchLabels:
      control-plane: controller-manager
  podMetricsEndpoints:
  - port: metrics
