apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  interval: 0h1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  #path: ./clusters/_shared_/namespaces-base
  path: ./clusters/production/namespaces
  prune: true
  validation: client
