apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  dependsOn:
    - name: sources
    - name: namespaces
  interval: 0h5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/_shared_/nginx
  prune: true
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx-ingress-controller
      namespace: nginx
