apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-state-metrics
spec:
  releaseName: kube-state-metrics
  chart:
    spec:
      chart: kube-state-metrics
      sourceRef:
        kind: HelmRepository
        name: stevehipwell.github.io
        namespace: flux-system
      version: "3.1.0"
  interval: 0h5m0s
  install:
    remediation:
      retries: 3
  # Default values
  values:
    args:
      - --kubelet-insecure-tls
