apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opa-gatekeeper
spec:
  releaseName: opa-gatekeeper
  chart:
    spec:
      chart: gatekeeper
      sourceRef:
        kind: HelmRepository
        name: gatekeeper
        namespace: flux-system
      version: "3.4.0"
  interval: 0h5m0s
  install:
    remediation:
      retries: 3
  # Default values
  values:
    postInstall:
      labelNamespace:
        enabled: false
  postRenderers: 
  - kustomize:
      patchesStrategicMerge:
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: gatekeeper-controller-manager
          namespace: gatekeeper-system
        spec:
          template:
            spec:
              containers:
              - name: manager
                args:
                - --port=8443
                - --logtostderr
                - --operation=webhook
                - --exempt-namespace=gatekeeper-system
                - --exempt-namespace=flux-system
                - --exempt-namespace=kube-system
                - --exempt-namespace=kube-node-lease
                - --exempt-namespace=kube-public
                - --exempt-namespace=podinfo
                - --exempt-namespace=redis
                - --exempt-namespace=default
                - --exempt-namespace=nginx
                - --exempt-namespace=production-test

