apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: ""
  labels:
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/name: metallb
  name: metallb-config
  namespace: metallb-system
data:
  config: |
    address-pools:
    - addresses:
      - 172.18.255.200-172.18.255.250
      name: kind-cluster-pool
      protocol: layer2
