apiVersion: v1
kind: ResourceQuota
metadata:
  name: flux-system-ns-quota
  namespace: flux-system
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "6"
    limits.memory: 6Gi
    pods: "20"
