apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cm-test
  namespace: flux-system
spec:
  dependsOn:
    - name: sources
  interval: 0h5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/staging/cm-test
  prune: true
  #validation: client
  validation: none
  force: true
