apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 0h5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure
  prune: true
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx-ingress-controller
      namespace: nginx
    - apiVersion: apps/v1
      kind: Deployment
      name: gatekeeper-controller-manager
      namespace: gatekeeper-system
    - apiVersion: templates.gatekeeper.sh/v1beta1
      kind: ConstraintTemplate
      name: k8srequiredlabels
      namespace: gatekeeper-system
