#apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
#kind: Kustomization
#metadata:
#  name: ingress-nginx-too
#  namespace: flux-system
#spec:
#  dependsOn:
#    - name: sources
#    - name: namespaces
#    - name: kube-prometheus-stack
#  interval: 0h5m0s
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  path: ./clusters/_shared_/ingress-nginx-too-base
#  prune: true
#  validation: client
#  healthChecks:
#    - apiVersion: apps/v1
#      kind: Deployment
#      name: ingress-nginx-too-controller
#      namespace: ingress-nginx-too
