apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  interval: 0h5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/staging/namespaces
  prune: true
  validation: client
