apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: opa-gatekeeper
  namespace: flux-system
spec:
  dependsOn:
    - name: sources
  interval: 0h5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  #path: ./clusters/_shared_/opa-gatekeeper-base
  path: ./clusters/staging/opa-gatekeeper
  prune: true
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: gatekeeper-controller-manager
      namespace: gatekeeper-system
