apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: policy-exceptions
  namespace: flux-system
spec:
  dependsOn:
    - name: sources
    - name: namespaces
    - name: opa-gatekeeper
  interval: 5m
  path: ./opa-policy-constraints
  prune: true
  sourceRef:
    kind: GitRepository
    name: policy-exceptions
  validation: none
