apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: policy
  namespace: flux-system
spec:
  dependsOn:
    - name: sources
    - name: namespaces
    - name: opa-gatekeeper
  interval: 5m
  path: "./clusters/_shared_/policy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: none
