kind: Provider
metadata:
  name: flux-system-provider
  namespace: flux-system
spec:
  type: github
  address: https://github.com/MxNxPx/flux2-kustomize-helm-example
  secretRef:
    name: github-pat
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: flux-system-alerts
  namespace: flux-system
spec:
  providerRef:
    name: flux-system-provider
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
    - kind: HelmRelease
      name: '*'
