apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  dependsOn:
    - name: sources
    - name: namespaces
  interval: 0h5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/_shared_/sealed-secrets-base
  prune: true
  validation: client
  values:
    # secretName: The name of the TLS secret containing the key used to encrypt secrets
    secretName: "sealed-secrets-key"
    dashboards:
      # If enabled, sealed-secrets will create a configmap with a dashboard in json that's going to be picked up by grafana
      # See https://github.com/helm/charts/tree/master/stable/grafana#configuration - `sidecar.dashboards.enabled`
      create: true
      # Extra labels to apply to the dashboard configmaps
      labels:
        grafana_dashboard: "1"
