apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opa-gatekeeper
spec:
  releaseName: opa-gatekeeper
  chart:
    spec:
      chart: gatekeeper
      sourceRef:
        kind: HelmRepository
        name: gatekeeper
        namespace: flux-system
      version: "3.4.0"
  interval: 0h5m0s
  install:
    remediation:
      retries: 3
  # Default values
  values:
    postInstall:
      labelNamespace:
        enabled: false
  postRenderers: 
    patchesStrategicMerge: gatekeeper-patch.yaml
