apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatekeeper-controller-manager
  namespace: gatekeeper-system
spec:
  template:
    spec:
      containers:
      - name: manager
        args:
        - --port=8443
        - --logtostderr
        - --operation=webhook
        - --exempt-namespace=gatekeeper-system
        - --exempt-namespace=kube-system
        - --exempt-namespace=kube-public
