apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stakater-reloader
spec:
  releaseName: stakater-reloader
  chart:
    spec:
      chart: reloader
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: flux-system
      version: "v0.0.89"
  interval: 0h1m0s
  install:
    remediation:
      retries: 3
