apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stakater-reloader
spec:
  releaseName: stakater-reloader
  chart:
    spec:
      # renovate: registryUrl=https://stakater.github.io/stakater-charts
      chart: reloader
      version: v0.0.89
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: flux-system
  interval: 0h1m0s
  install:
    remediation:
      retries: 3
