apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  releaseName: metrics-server
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "5.8.9"
  interval: 0h1m0s
  install:
    remediation:
      retries: 3
  values:
    extraArgs:
      kubelet-insecure-tls: true
      kubelet-preferred-address-types: ${metrics_server_address_types:=InternalIP}
    apiService:
      create: true
