apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wave-k8s
spec:
  releaseName: wave-k8s
  chart:
    spec:
      chart: wave
      sourceRef:
        kind: HelmRepository
        name: wave-k8s
        namespace: flux-system
      version: "2.0.0"
  interval: 0h1m0s
  install:
    remediation:
      retries: 3
