apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-problem-detector
spec:
  releaseName: node-problem-detector
  chart:
    spec:
      chart: node-problem-detector
      sourceRef:
        kind: HelmRepository
        name: deliveryhero
        namespace: flux-system
      #version: "2.0.1"
      version: "2.0.2"
  interval: 0h1m0s
  install:
    remediation:
      retries: 3
