apiVersion: v1
kind: Secret
metadata:
  annotations:
  labels:
  name: kube-prometheus-stack-grafana-custom
  namespace: kube-system
type: Opaque
data:
  admin-password: bXB0ZXN0
  admin-user: YWRtaW4=
  ldap-toml: ""
