apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
spec:
  releaseName: sealed-secrets
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: bitnami-labs-sealed-secrets
        namespace: flux-system
      version: "1.16.1"
      #version: "1.13.2"
  interval: 0h1m0s
  install:
    replace: true
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    remediation:
      retries: 3
    crds: CreateReplace
    cleanupOnFail: true
  values:
    commandArgs: --key-renew-period 0
    # secretName: The name of the TLS secret containing the key used to encrypt secrets
#    secretName: "mycustomkeys"
    
